AWSTemplateFormatVersion: 2010-09-09
Description: AWS Cloud Formation - Practice 2 - David Rojo

# ami id:       (ubuntu 18.04 ireland) ami-06fd78dc2f0b69910
# bucket:       testp2.cf.cloudapps.david
# db password:  springaws
# jar location: https://github.com/david-rojo/cloudApps-aws-cloudFormation/releases/download/v1/app-cf.jar

Parameters:

  # ami id
  AMIId:
    Description: AMI to use, it must be an AMI on the current region and must be Ubuntu 18.04 (default is AMI id for us-east-1 region)
    Type: 'AWS::EC2::Image::Id'
    # Default value is AMI id of ubuntu 18.04 in us-east-1 region
    Default: ami-013f17f36f8b1fefb

  # db password
  DBPassword:
    Description: RDS database password
    Type: String
    NoEcho: true

  # S3 bucket name
  BucketName:
    Description: S3 bucket name
    Type: String

  # jar url location (default: https://s3.amazonaws.com/practica-2.cloud.michel/app.jar)
  JarLocationUrl:
    Description: URL of the application jar (default is the url provided in the practice instructions)
    Type: String
    # Default location defined in the instructions of the practice
    Default: https://s3.amazonaws.com/practica-2.cloud.michel/app.jar

  KeyName: # TEST
    Description: Name of an existing EC2 KeyPair to enable SSH access to the instance
    Type: AWS::EC2::KeyPair::KeyName
    ConstraintDescription: must be the name of an existing EC2 KeyPair.

Resources:

  # S3 write access role
  s3WriteAccessRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service: ec2.amazonaws.com
            Action: sts:AssumeRole
      Path: /

  # profile for ec2 instance
  # is not possible to assign directly a role to an ec2 instance
  # is needed an instance profile as a wrapper for the role
  rootS3InstanceProfile:
    Type: AWS::IAM::InstanceProfile
    Properties:
      Path: /
      Roles:
        - !Ref s3WriteAccessRole

  # EC2 security group
  ec2SecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupName: p2-443
      GroupDescription: "Security Group for Java web app with ingress port 443"
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: '443'
          ToPort: '443'
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp # TEST
          FromPort: '22'
          ToPort: '22'
          CidrIp: 0.0.0.0/0

  # RDS security group
  rdsSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: "Security Group for MySQL RDS"
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: '3306'
          ToPort: '3306'
          # Only allowed access to the instances of this SG
          SourceSecurityGroupName: !Ref ec2SecurityGroup

  # db instance
  rdsDbInstance:
    Type: AWS::RDS::DBInstance
    Properties:
      DBInstanceClass: db.t2.micro
      AllocatedStorage: 10
      AllowMajorVersionUpgrade: false
      AutoMinorVersionUpgrade: false
      DBInstanceIdentifier: springaws
      DBName: springaws
      Engine: mysql
      EngineVersion: 8.0.20
      MasterUsername: springaws
      MasterUserPassword: !Ref DBPassword
      MultiAZ: false
      PubliclyAccessible: false
      StorageEncrypted: false
      VPCSecurityGroups:
        - !GetAtt rdsSecurityGroup.GroupId
      Tags:
        - Key: Name
          Value: mca-aws-cf-practice-2

  # S3 bucket
  s3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Ref BucketName
      AccessControl: PublicRead
      WebsiteConfiguration:
        IndexDocument: index.html
        ErrorDocument: error.html

  # EC2 instance
  ec2Instance:
    Type: AWS::EC2::Instance
    Properties:
      IamInstanceProfile: !Ref rootS3InstanceProfile
      KeyName: !Ref KeyName # TEST
      ImageId: !Ref AMIId
      InstanceType: t2.micro
      Monitoring: true
      SecurityGroups:
        - !Ref ec2SecurityGroup
      UserData:
        Fn::Base64:
          Fn::Sub:
          - |
            #!/bin/bash -ex
            sudo apt update && apt install -y openjdk-11-jre-headless
            wget -O /home/ubuntu/app.jar ${JAR_LOCATION_URL}
            sudo java -jar \
                -Dspring.profiles.active=production \
                /home/ubuntu/app.jar \
                --server.port=443 \
                --spring.datasource.url=jdbc:mysql://${RDS_DNS}/${RDS_DATABASE} \
                --spring.datasource.username=${RDS_USER} \
                --spring.datasource.password=${RDS_PASS} \
                --amazon.s3.bucket-name=${BUCKET_NAME} \
                --amazon.s3.endpoint=https://s3.amazonaws.com/${BUCKET_NAME}/ \
                --amazon.s3.region=${REGION}
          - JAR_LOCATION_URL: !Ref JarLocationUrl
            RDS_DNS: !GetAtt rdsDbInstance.Endpoint.Address
            RDS_DATABASE: springaws
            RDS_USER: springaws
            RDS_PASS: !Ref DBPassword
            BUCKET_NAME: !Ref BucketName
            REGION: !Ref AWS::Region            
      Tags:
        - Key: Name
          Value: mca-aws-cf-practice-2
    DependsOn: rdsDbInstance

  # policy is associated with the role
  RolePolicies:
    Type: AWS::IAM::Policy
    DependsOn:
      - ec2Instance
    Properties:
      PolicyName: Ec2InstancePolicy
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Action: 's3:*'
            Resource: '*'
      Roles:
        - !Ref s3WriteAccessRole

Outputs:

  # application endpoint
  WebSiteURL:
    Value:
      !Join
        - ''
        - - "https://"
          - !GetAtt ec2Instance.PublicDnsName
    Description: "Practice 2 - Application website"